export const ClayTheme = {
  colors: {
    primary: '#6366f1',
    primaryLight: '#a5b4fc',
    secondary: '#f59e0b',
    accent: '#10b981',
    background: '#f8fafc',
    surface: '#ffffff',
    clay: {
      light: '#f1f5f9',
      medium: '#e2e8f0',
      dark: '#cbd5e1',
      shadow: '#94a3b8',
    },
    text: {
      primary: '#1e293b',
      secondary: '#64748b',
      light: '#94a3b8',
    },
    gradient: {
      primary: ['#6366f1', '#8b5cf6'] as const,
      secondary: ['#f59e0b', '#f97316'] as const,
      accent: ['#10b981', '#059669'] as const,
      clay: ['#f8fafc', '#f1f5f9'] as const,
    },
    status: {
      success: '#10b981',
      warning: '#f59e0b',
      error: '#ef4444',
      info: '#6366f1',
    },
  },
  shadows: {
    clay: {
      shadowColor: '#cbd5e1',
      shadowOffset: { width: 8, height: 8 },
      shadowOpacity: 0.3,
      shadowRadius: 16,
      elevation: 8,
    },
    clayInset: {
      shadowColor: '#ffffff',
      shadowOffset: { width: -4, height: -4 },
      shadowOpacity: 0.7,
      shadowRadius: 8,
    },
    clayPressed: {
      shadowColor: '#cbd5e1',
      shadowOffset: { width: 4, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 8,
      elevation: 4,
    },
    claySubtle: {
      shadowColor: '#cbd5e1',
      shadowOffset: { width: 2, height: 2 },
      shadowOpacity: 0.15,
      shadowRadius: 4,
      elevation: 2,
    },
  },
  borderRadius: {
    small: 8,
    medium: 16,
    large: 24,
    extraLarge: 32,
    round: 999,
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
};

export const clayMorphStyles = {
  container: {
    backgroundColor: ClayTheme.colors.clay.light,
    borderRadius: ClayTheme.borderRadius.large,
    padding: ClayTheme.spacing.lg,
    ...ClayTheme.shadows.clay,
  },
  button: {
    backgroundColor: ClayTheme.colors.surface,
    borderRadius: ClayTheme.borderRadius.medium,
    padding: ClayTheme.spacing.md,
    ...ClayTheme.shadows.clay,
  },
  buttonPressed: {
    backgroundColor: ClayTheme.colors.clay.medium,
    ...ClayTheme.shadows.clayPressed,
  },
  card: {
    backgroundColor: ClayTheme.colors.surface,
    borderRadius: ClayTheme.borderRadius.large,
    padding: ClayTheme.spacing.lg,
    margin: ClayTheme.spacing.sm,
    ...ClayTheme.shadows.clay,
  },
  cardSubtle: {
    backgroundColor: ClayTheme.colors.surface,
    borderRadius: ClayTheme.borderRadius.medium,
    padding: ClayTheme.spacing.md,
    margin: ClayTheme.spacing.xs,
    ...ClayTheme.shadows.claySubtle,
  },
  input: {
    backgroundColor: ClayTheme.colors.surface,
    borderRadius: ClayTheme.borderRadius.medium,
    padding: ClayTheme.spacing.md,
    borderWidth: 0,
    color: ClayTheme.colors.text.primary,
    ...ClayTheme.shadows.clay,
  },
  chip: {
    backgroundColor: ClayTheme.colors.surface,
    borderRadius: ClayTheme.borderRadius.large,
    paddingHorizontal: ClayTheme.spacing.md,
    paddingVertical: ClayTheme.spacing.sm,
    ...ClayTheme.shadows.clay,
  },
  chipSelected: {
    backgroundColor: ClayTheme.colors.primary,
    ...ClayTheme.shadows.clayPressed,
  },
  header: {
    backgroundColor: ClayTheme.colors.surface,
    borderRadius: 0,
    padding: ClayTheme.spacing.md,
    ...ClayTheme.shadows.clay,
  },
  fab: {
    backgroundColor: ClayTheme.colors.primary,
    borderRadius: ClayTheme.borderRadius.round,
    width: 56,
    height: 56,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
    ...ClayTheme.shadows.clay,
  },
};
